# This config contains a load of extra options
# You can enable / disable features here.

#If you have no idea how to use a config don't edit this.

#Enable the plugin? Change it to "yes" or "no"
enabled: "yes"

#How much health should a player get when mushroom stew is taped?
health-earned: "3.5"

######
# Set this to "yes" to send a message when stew is taped, Otherwise set it to "no".
send-message-when-stew-tapped: "no"

#If the above is set to "yes", what should the message be?
message-if-enabled: "+3.5 hearts for drinking stew."
######
